### ISSUE TITLE
Get top 100 podcast

### ISSUE THREAD

**Issue by samjam48** [syncify-team/syncify-app#45]
Get details of podcasts and hard code into the app.
Make a list of podcast names and feeds.
Make file for each podcast.
Get the top 10 podcasts for each genre

Write script to run that pulls podcast details
convert podcast to usable JS file

**Comment by samjam48** [comment]
@caiokf Can you let us know how you converted the XML file into the javascript and if you have anything ready-made or a tool you used?
I'm guessing it's just a standard set of rules for parsing information but would be good to know

**Comment by caiokf** [comment]
you can use the feedparser.js which is in services, which is recommended for scripting many podcasts. Or to test one, you can just find an rss to json online parser.

**Comment by vine-d** [comment]
I made a new branch **get-top-podcasts** and commited a very simple script that gets top # podcasts a save to JSON files.
Also uploaded 70 json files to data-new folder inside src/module/podcasts
