### ISSUE TITLE
bug - children with same name

### ISSUE THREAD

**Issue by samjam48** [syncify-team/syncify-app#61]
When user goes to view episodes of a podcast the warning shows:
`Encountered two children with the same key` 

It seems to slow down and get buggy if i go back and forth into different podcasts browsing.

**Comment by caiokf** [comment]
@samjam48 Could you give some examples of a couple episodes that you see this happening with? Otherwise it could be some trial and error or unnecessary digging. Also, a screenshot could be helpful.

**Comment by samjam48** [comment]
Seems to not be occurring now. Did @nataphilips  update the episode keys with some of her other changes on these screens?
